name: ci-tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cmd/**
      - pkg/**
  pull_request:
    branches:
      - main
    paths:
      - cmd/**
      - pkg/**

jobs:
  test-labgob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd pkg/labgob && go test

  test-raft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd pkg/raft && go test